### ISSUE TITLE
Old A record format?

### ISSUE THREAD

**Issue by Turbo87** [Joey9801/igc-rs#2]
It seems that this crate implements an older variant of the A record format. The AFAIK most recent variant is specified on page 22 of https://github.com/Turbo87/rust-igc/blob/master/docs/IGC_FR_Spec_with_AL4a_2016-4-10.pdf as `A MMM NNN` (instead of `A M NNNNN`). There are also a few other variants commonly in use that encode other data in there. We might have to read the first `M` byte, and figure out from that what variant to use.

**Comment by Joey9801** [comment]
Indeed, I had been coding to version 1.0 of the spec.
I'm happy to update the A record parsing to the newer format - could you elaborate on the other variants you've come across?

**Comment by Turbo87** [comment]
LX devices for example encode the flight number in there: https://github.com/Turbo87/igc-parser/blob/9f12d27b1ea31e8cc3d37e16469354165885bf37/fixtures/1G_77fv6m71.igc#L1

Some older Filser/LX devices also seem to use a combination of both specs (`MMMNNNNN`): https://github.com/XCSoar/XCSoar/blob/f6a2566c2f5176be9c77f950c9f8715a3ddfb3f4/test/data/lxn_to_igc/18BF14K1.igc#L1

In those cases they seem to have used a purely numeric logger ID though, so we should be able to detect that. It could then be converted to a proper ID using base36, but since this is a low-level parser it should probably just keep the raw data.
