### ISSUE TITLE
Date uses 2000+ years

### ISSUE THREAD

**Issue by Turbo87** [Joey9801/igc-rs#3]
The crate claims that it is low-level, but it seems that the `Date` parser makes an assumption which goes against that claim. I would suggest that the low-level parser should only parse the year as a two-digit number and that a higher-level parser could then figure out the correct date on top of that.

If we keep the code like this I would suggest to at least use e.g. 1980 as the baseline, as there are plenty of IGC files from before 2000 around.

**Comment by Joey9801** [comment]
Good point, I'll remove the millennium from the date entirely.
