### ISSUE TITLE
B record does not allow negative altitudes

### ISSUE THREAD

**Issue by Turbo87** [Joey9801/igc-rs#4]
The IGC file spec specifies that altitudes can be negative (necessary e.g. in the Netherlands). That means `u16` would have to change to `i16`. That however would shrink the range of usable positive values in an unreasonable amount, so I would suggest to bite the bullet and use `i32` instead.

**Comment by Joey9801** [comment]
Indeed, good spot!

**Comment by Joey9801** [comment]
I think an `i16` would still be sufficient, the maximum representable altitude would still be ~30,000ft higher than the current altitude record for the Perlan Project, and >15,000ft higher than their objective altitude.

**Comment by Turbo87** [comment]
I guess i16 is indeed enough. We might want to add tests for these boundaries though and test for the errors.
